# Site settings
title: Courtauld Website User Guide
description: > # this means to ignore newlines until "baseurl:"
  This website is the online user guide for people editing The Courtauld's WordPress website.

email: website@courtauld.ac.uk

baseurl: "/guide" # the subpath of your site, e.g. /blog
url: "http://courtauld.github.io" # the base hostname & protocol for your site

permalink: pretty

gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown

# Collections
collections:
  navigation:
    output: true
    layout: page
  news:
    output: true
    layout: page
  page:
    output: true
    layout: page
  event:
    output: true
    layout: page
  profile:
    output: true
    layout: page
  media:
    output: true
    layout: page
  publishing:
    output: true
    layout: page
