# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Courtauld Website User Guide
email: website@courtauld.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  This website is the online user guide for people editing The Courtauld's WordPress website.
baseurl: "/guide" # the subpath of your site, e.g. /blog
url: "http://courtauld.github.io" # the base hostname & protocol for your site

permalink: pretty

gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown

# Collections
collections:
  event:
    output: true
    permalink: /event/:path/
  media:
    output: true
    permalink: /media/:path/
  navigation:
    output: true
    permalink: /navigation/:path/
  news:
    output: true
    permalink: /news/:path/
  page:
    output: true
    permalink: /page/:path/
  profile:
    output: true
    permalink: /profile/:path/
  publishing:
    output: true
    permalink: /publishing/:path/
