# Site settings
title: Courtauld Website User Guide
description: > # this means to ignore newlines until "baseurl:"
  This website is the online user guide for people editing The Courtauld's WordPress website.

email: website@courtauld.ac.uk

baseurl: "/guide" # the subpath of your site, e.g. /blog
url: "http://courtauld.github.io" # the base hostname & protocol for your site

permalink: pretty

# Build settings
markdown: kramdown

# Exclude from build

exclude: [posts]

# Collections
collections:
  navigation:
    output: true
  news:
    output: true
  page:
    output: true
  event:
    output: true
  profile:
    output: true
  media:
    output: true
  publishing:
    output: false

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
